apiVersion: v1
kind: Service
metadata:
  name: rp-west-multicluster-peer
  namespace: redpanda
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: rp-west
  ports:
    - name: raft
      port: 9443
      targetPort: 9443
      protocol: TCP
  publishNotReadyAddresses: true
